// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmE7qRtwT3A9nQ352soOBqDREtBkKO-J8',
    appId: '1:383461734900:web:bb37f411080346905821a1',
    messagingSenderId: '383461734900',
    projectId: 'herb-id-app',
    authDomain: 'herb-id-app.firebaseapp.com',
    storageBucket: 'herb-id-app.appspot.com',
    measurementId: 'G-BHPS3DSMH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_t8bSUlTAzOAsuE1fqudLAeQO1h1k-DU',
    appId: '1:383461734900:android:e8a52825a6fa1f495821a1',
    messagingSenderId: '383461734900',
    projectId: 'herb-id-app',
    storageBucket: 'herb-id-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVbk3Hc1g5tHGDl8GfFmMOVvq-DGKW7s',
    appId: '1:383461734900:ios:d470bc48dd1c9dc65821a1',
    messagingSenderId: '383461734900',
    projectId: 'herb-id-app',
    storageBucket: 'herb-id-app.appspot.com',
    androidClientId:
        '383461734900-257v649h4cc76jqfp88gsc11t9ho3qee.apps.googleusercontent.com',
    iosClientId:
        '383461734900-4dl637iq7e3gfsjtmvkobu27tvlu7dg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.herbIdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHVbk3Hc1g5tHGDl8GfFmMOVvq-DGKW7s',
    appId: '1:383461734900:ios:25d7cb3712b5155c5821a1',
    messagingSenderId: '383461734900',
    projectId: 'herb-id-app',
    storageBucket: 'herb-id-app.appspot.com',
    androidClientId:
        '383461734900-257v649h4cc76jqfp88gsc11t9ho3qee.apps.googleusercontent.com',
    iosClientId:
        '383461734900-bat3gl07gkgt608qiqhage5v2ibti1fv.apps.googleusercontent.com',
    iosBundleId: 'com.example.herbIdApp.RunnerTests',
  );
}
