name: HerdID
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  http: ^1.1.0
  dartz: ^0.10.1
  either_dart: ^1.0.0
  flutter:
    sdk: flutter
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_svg: ^2.0.7
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^4.0.2
  google_fonts: ^5.1.0
  image: ^4.1.3
  firebase_core: ^2.19.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.12.0
  permission_handler: ^11.3.0
  tutorial_coach_mark: ^1.2.11
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/jpg/

